#pragma once

//#define GPIO_HIBUS_TX_PIN  GPIO_NUM_2 // GPIO_NUM_35
//#define GPIO_HIBUS_RX_PIN  GPIO_NUM_1 //GPIO_NUM_34

#define GPIO_BUZZER  GPIO_NUM_6

#define GPIO_HIBUS_TX_PIN  GPIO_NUM_35
#define GPIO_HIBUS_RX_PIN  GPIO_NUM_34

#define GPIO_LEDSTRIP  GPIO_NUM_38

// TCA9555 I2C
#define GPIO_I2C_SDA  GPIO_NUM_37
#define GPIO_I2C_SCL  GPIO_NUM_36

//TCA9555 interrupt gpio
#define GPIO_INTTCA9555  GPIO_NUM_33

#define NUM_OF_CHANNELS 32

#define NUM_OF_LEDS NUM_OF_CHANNELS


